### ISSUE TITLE
Feature Request: provide groups/project via CLI parameter

### ISSUE THREAD

**Issue by shaneog** [flexoid/mergentle-reminder#1]
Ideally I would like to create a single Docker image that I could run via GitLab scheduled tasks for multiple projects/groups.
In that case I would want to pass the list of Groups or Projects via a CLI parameter rather than via a config file.

Is that possible?

**Example:** 

```yml
groups:
  - id: 1
  - id: 2
```
would be equivalent to:

```sh
GROUPS=1,2
```

**Comment by flexoid** [comment]
Hey @shaneog.
Thanks for the feedback!

Just added an ability of full configuration via ENV variables. Check out an updated README.

Please let me know if it works for you.

**Comment by shaneog** [comment]
Thank you!
